### ISSUE TITLE
This is still an intel app that requires Rosetta. Any plans for a native Apple silicon one?

### ISSUE THREAD

**Issue by Timotei-S** [fredericocurti/night-shift-slider#1]
This is the only app of its kind, so thank you anyway!! I really need it!

**Comment by fredericocurti** [comment]
Hey, glad you enjoy it! For now I would recommend https://github.com/thompsonate/Shifty, it has more features :) Once I get some time i'll recompile this to apple silicon!

**Comment by Timotei-S** [comment]
Yeah, I used it a little bit. Seems more buggy though.

I'd rather install Rosetta and use your app.

**Comment by fredericocurti** [comment]
Hey @Timotei-S, just released a Apple Silicon build :)
